apiVersion: v1
kind: Service
metadata:
  name: splunk-s2s-kafka-connect-lb
  labels:
    appName: splunk-connect
spec:
  type: LoadBalancer
  ports:
  - port: 9997
    targetPort: 9997
    protocol: TCP
  selector:
    appName: splunk-connect
